[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"  # 18 also works, but 20 is safest with Vite 5

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

